server {
    listen 80;

    location / {
        # public ではなく html (つまり app/front 直下) をルートにする
        root /usr/share/nginx/html;
        index public/index.html;
        # ファイルがなかったら、とりあえず index.html を見に行く
        try_files $uri $uri/ /public/index.html;
    }

    location /api {
        proxy_pass http://backend:8000/api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}